target-version = "py311"
line-length = 100
extend-exclude = ["frontend", ".venv", "venv"]

[lint]
select = ["E","F","W","I","B","UP","S"]
ignore = ["E501"]

[lint.per-file-ignores]
"tests/**" = ["S101","S112"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
